platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'LCShare' do

pod 'LCShare', :path => '../'
pod 'LCMediator', :path => '../../LCMediator'
pod 'LCBase', :path => '../../LCBase'

pod 'AFNetworking'
pod 'Masonry'
#pod 'Weibo_SDK', :git => 'https://github.com/sinaweibosdk/weibo_ios_sdk.git'

end
