platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'LCMoment' do

pod 'LCMoment', :path => '../'
pod 'LCMediator', :path => '../../LCMediator'
pod 'LCBase', :path => '../../LCBase'

pod 'AFNetworking'
pod 'Masonry'

end
